### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Winfidonarleyan** [WarheadCore/WarheadCore#17]
# Todo list
### 1. Core/Global
- [x] rework mute system 097df4e
- [x] support off Cmake pch 7e7214f
- [x] correct GitRevision in Player.cpp e9c0e2f
- [x] fix eventmap system e633723
- [x] improve eventmap 300e008
- [x] `ABORT_MSG ` bfcdee7
- [x] log commands (not used now) c13f8d9
- [x] replace all logs to new 99d7977
- [x] delete extralogs (delete macros)
- [ ] replace to chrono literals
- [ ] add time locales
- [ ] enable `achievement_locale`
- [ ] implement `DBReloader` #19 
- [ ] `creature_text_locale`
- [ ] rev between factions
- [x] https://github.com/TrinityCore/TrinityCore/pull/22408 b9d67e749
- [x] 0fe9d7833
- [ ] https://github.com/TrinityCore/TrinityCore/commit/34b63019ae977ef29606e8b1e0acc2442a63e295 #131
- [ ] https://github.com/TrinityCore/TrinityCore/commit/00f3b01ea72069671b928f8b196a89d4b1a39d55 #131

### 2. Core/Module
- [x] fix module `DungeonBuff` 1a0c72e
- [x] disable all modules in config default a75b9d0
- [x] add ips shop variant in DB 848d8b0
- [x] rework external mail (task, func) a2c7525
- [x] fix module (sql) `OnlineReward` 31963e6
- [x] Exmail 12+ items 17f3df1
- [x] locale all modules
- [x] implement GLS #15
- [ ] implement EventSystem
- [x] Boss announce (locale, world boss only)
- [x] Add suport in `LevelReward` ExMail class #126
- [x] Separate channels in `mod-anti-ad` #129
- [ ] Add support replace bad word `****` in `mod-anti-ad`

### 3. Core/Scripts
- [ ] Fix Nax `events.ScheduleEvent(EVENT_SPELL_DEATHBLOOM, 6s);` to `2min` 

### 4. Modules/Locale
- [x] mod-boss-announcer #122
- [x] mod-buff-command #128
- [x] mod-level-reward #124
- [x] mod-notify-muted #127
- [x] mod-online-reward 74bcf1e5d
- [x] mod-transmogrification #118

### 5. Modules/Locale
- [ ] Restruct string checks

### 6. Level up item
- [ ] Implement module

### 7.  Chrono
- [ ] Check `Scripts/Northrend`

**Comment by Tooldev94** [comment]
4. BAN VISTE ALL MODS ABOUT HIM CRASH ALL MY SERVER MANGOS

**Comment by Winfidonarleyan** [comment]
Added `4. Modules/Locale`

**Comment by Winfidonarleyan** [comment]
Added `5. Modules/Locale`

**Comment by Winfidonarleyan** [comment]
Complete locales all default modules `4. Modules/Locale`

**Comment by Winfidonarleyan** [comment]
Added:
- `6. Level up item`
- `7. Global/Locale`
